version: "3"

services:
  mysql_db:
    image: mysql:5.7
    container_name: tpgenie_db
    restart: unless-stopped
    volumes:
      - ./sql-data:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - tpgenie_db_nw
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce

  nginx:
    image: nginx:latest
    container_name: tpgenie_nginx
    restart: unless-stopped
    volumes:
      - ./cfg/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    networks:
      - tpgenie_web_nw
    depends_on:
      - app_server

  app_server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    restart: unless-stopped
    volumes:
      - .:/go/src/app
    depends_on:
      - "mysql_db"
    ports:
      - 8998
    networks:
      - tpgenie_db_nw
      - tpgenie_web_nw

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
    networks:
      - tpgenie_db_nw

networks:
  tpgenie_db_nw:
    driver: bridge
  tpgenie_web_nw:
    driver: bridge
